name: Test
description: Run tests
inputs:
  rubygems_api_key:
    description: RubyGems API key
    required: true
runs:
  using: composite
  steps:
    - run: mkdir -p ~/.gem
      shell: bash
    - run: |
        cat <<-YAML > ~/.gem/credentials
        ---
        :rubygems_api_key: ${{ inputs.rubygems_api_key }}
        YAML
      shell: bash
