name: Test and Release
on:
  pull_request:
  push:
  release:
    types:
      - published
jobs:
  test:
    name: >-
      Test
      [Ruby ${{ matrix.ruby-version }},
      ActiveSupport ${{ matrix.activesupport-version }}]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        activesupport-version:
          - ~> 3.2
          - ~> 4.0
          - ~> 5.0
          - ~> 6.0
          - ~> 7.0
        ruby-version:
          - "3.1"
          - "3.2"
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - uses: ./.github/actions/test
        with:
          activesupport-version: ${{ matrix.activesupport-version }}
  push:
    name: Publish Gem
    if: ${{ github.event.release }}
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - uses: ./.github/actions/setup-rubygems
        with:
          rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
      - run: bundle install
      - run: bundle exec rake gem:push
