name: test
on:
  pull_request:
  push:
jobs:
  test:
    name: >-
      Ruby ${{ matrix.ruby }}, ActiveSupport ~> ${{ matrix.activesupport }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        activesupport:
          - "3.2"
          - "4.0"
          - "5.0"
          - "6.0"
          - "7.0"
        ruby:
          - "3.1"
          - "3.2"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          ruby-version: ${{ matrix.ruby }}
          activesupport-version: ${{ matrix.activesupport }}
