name: Test and Release
on:
  pull_request:
  push:
  release:
    types:
      - published
jobs:
  test:
    name: >-
      Ruby ${{ matrix.ruby }}, ActiveSupport ~> ${{ matrix.activesupport }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        activesupport:
          - "3.2"
          - "4.0"
          - "5.0"
          - "6.0"
          - "7.0"
        ruby:
          - "3.1"
          - "3.2"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          ruby-version: ${{ matrix.ruby }}
          activesupport-version: ${{ matrix.activesupport }}
  push:
    if: ${{ github.event.release.published }}
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-rubygems
        with:
          rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
      - run: bundle exec rake gem:push
